http:
  port: 8080
admin:
  port: 9876
  host: localhost

# 1. Definimos las rutas de entrada (Lo que escribe el frontend)
apiEndpoints:
  mascotas_publico:
    paths: '/api/mascotas/reportes'
    methods: ['GET']
  mascotas_api:
    paths: '/api/mascotas/*'
  # 1. El endpoint público (más específico)
  localizacion_api:
    host: '*'
    paths: '/api/localizacion/*'
  auth_api:
    paths: '/api/auth/*'
  users_api:
    paths: '/api/users/*'
  tickets_api:
    paths: ['/api/tickets', '/api/tickets/*']
  chatbot_api:
    paths: '/api/chatbot/*'
  health_api:
    paths: '/health'

serviceEndpoints:
  bff_service:
    url: 'http://backforfrontend:3000'

# 2. Declaramos las políticas que vamos a usar
policies:
  - jwt
  - request-transformer
  - proxy
  - circuit-breaker
  - health-check
  - rate-limit   
  - cors     
  


# 3. Creamos un "tubo" (pipeline) para cada microservicio
pipelines:
 # --- PIPELINE PÚBLICO MASCOTAS (sin JWT) ---
  mascotas_publico_pipeline:
    apiEndpoints:
      - mascotas_publico
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: 'GET'
      - proxy:
          - action:
              serviceEndpoint: bff_service
              stripPath: false

  # --- PIPELINE PARA MASCOTAS ---
  mascotas_pipeline:
    apiEndpoints:
      - mascotas_api
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: 'GET,POST,PUT,DELETE,PATCH'
      - rate-limit:
          - action:
              max: 100
              windowMs: 900000
              delayAfter: 0
              delayMs: 0
              message: 'Demasiadas peticiones desde esta IP.'
      - jwt:
          - action:
              secretOrPublicKey: '6dcc110adf4dcde1015a418452ec8ca39780835ef83d28b13b165799a0525f264594d585080db90d09b8b9d4661507e40d67d5d2ae7673fb0b92719a18233213'
              checkCredentialExistence: false
      - request-transformer:
          - action:
              headers:
                add:
                  x-user-id: req.user.id
                  x-user-role: req.user.role
      - proxy:
          - action:
              serviceEndpoint: bff_service
              stripPath: false

  # ==========================================
  # PIPELINE LOCALIZACIÓN (Solo Lectura)
  # ==========================================
  localizacion_pipeline:
    apiEndpoints:
      - localizacion_api
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: 'GET,OPTIONS'
      - proxy:
          - action:
              serviceEndpoint: bff_service
              stripPath: false

  # ==========================================
  # PIPELINE AUTH (delega a BFF -> ms-auth)
  # ==========================================
  auth_pipeline:
    apiEndpoints:
      - auth_api
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: 'GET,POST,PUT,DELETE,PATCH'
      - rate-limit:
          - action:
              max: 100
              windowMs: 900000
              delayAfter: 0
              delayMs: 0
              message: 'Demasiadas peticiones desde esta IP.'
      - proxy:
          - action:
              serviceEndpoint: bff_service
              stripPath: false

  # ==========================================
  # PIPELINE USERS (delega a BFF -> ms-users)
  # ==========================================
  users_pipeline:
    apiEndpoints:
      - users_api
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: 'GET,POST,PUT,DELETE,PATCH'
      - rate-limit:
          - action:
              max: 100
              windowMs: 900000
              delayAfter: 0
              delayMs: 0
              message: 'Demasiadas peticiones desde esta IP.'
      - proxy:
          - action:
              serviceEndpoint: bff_service
              stripPath: false

  # ==========================================
  # PIPELINE SOPORTE (delega a BFF -> ms-soporte)
  # ==========================================
  tickets_pipeline:
    apiEndpoints:
      - tickets_api
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: 'GET,POST,PUT,DELETE,PATCH'
      - rate-limit:
          - action:
              max: 100
              windowMs: 900000
              delayAfter: 0
              delayMs: 0
              message: 'Demasiadas peticiones desde esta IP.'
      - proxy:
          - action:
              serviceEndpoint: bff_service
              stripPath: false

  chatbot_pipeline:
    apiEndpoints:
      - chatbot_api
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: 'GET,POST,PUT,DELETE,PATCH'
      - rate-limit:
          - action:
              max: 100
              windowMs: 900000
              delayAfter: 0
              delayMs: 0
              message: 'Demasiadas peticiones desde esta IP.'
      - proxy:
          - action:
              serviceEndpoint: bff_service
              stripPath: false

  # --- PIPELINE PARA HEALTH ---
  health_pipeline:
      apiEndpoints:
        - health_api
      policies:
        - health-check:
            - action: {}